-- =============================================================
-- Slovak Chart of Accounts (Účtovná osnova)
-- System-level defaults (organization_id IS NULL, is_system = TRUE)
-- Based on Opatrenie MF SR č. 23054/2002-92
-- =============================================================

-- Class 0 — Dlhodobý majetok (Long-term Assets)
INSERT INTO chart_of_accounts (organization_id, account_number, account_name, account_class, account_type, is_system) VALUES
  (NULL, '01', 'Dlhodobý nehmotný majetok', '0', 'asset', TRUE),
  (NULL, '011', 'Zriaďovacie náklady', '0', 'asset', TRUE),
  (NULL, '012', 'Aktivované náklady na vývoj', '0', 'asset', TRUE),
  (NULL, '013', 'Softvér', '0', 'asset', TRUE),
  (NULL, '014', 'Oceniteľné práva', '0', 'asset', TRUE),
  (NULL, '015', 'Goodwill', '0', 'asset', TRUE),
  (NULL, '019', 'Ostatný dlhodobý nehmotný majetok', '0', 'asset', TRUE),
  (NULL, '02', 'Dlhodobý hmotný majetok – odpisovaný', '0', 'asset', TRUE),
  (NULL, '021', 'Stavby', '0', 'asset', TRUE),
  (NULL, '022', 'Samostatné hnuteľné veci a súbory', '0', 'asset', TRUE),
  (NULL, '023', 'Dopravné prostriedky', '0', 'asset', TRUE),
  (NULL, '025', 'Pestovateľské celky trvalých porastov', '0', 'asset', TRUE),
  (NULL, '029', 'Ostatný dlhodobý hmotný majetok', '0', 'asset', TRUE),
  (NULL, '03', 'Dlhodobý hmotný majetok – neodpisovaný', '0', 'asset', TRUE),
  (NULL, '031', 'Pozemky', '0', 'asset', TRUE),
  (NULL, '032', 'Umelecké diela a zbierky', '0', 'asset', TRUE),
  (NULL, '04', 'Obstaranie dlhodobého majetku', '0', 'asset', TRUE),
  (NULL, '041', 'Obstaranie dlhodobého nehmotného majetku', '0', 'asset', TRUE),
  (NULL, '042', 'Obstaranie dlhodobého hmotného majetku', '0', 'asset', TRUE),
  (NULL, '05', 'Poskytnuté preddavky na dlhodobý majetok', '0', 'asset', TRUE),
  (NULL, '051', 'Poskytnuté preddavky na DNM', '0', 'asset', TRUE),
  (NULL, '052', 'Poskytnuté preddavky na DHM', '0', 'asset', TRUE),
  (NULL, '06', 'Dlhodobý finančný majetok', '0', 'asset', TRUE),
  (NULL, '061', 'Podielové cenné papiere a podiely v dcérskej účtovnej jednotke', '0', 'asset', TRUE),
  (NULL, '062', 'Podielové cenné papiere a podiely v spoločnosti s podstatným vplyvom', '0', 'asset', TRUE),
  (NULL, '063', 'Realizovateľné cenné papiere a podiely', '0', 'asset', TRUE),
  (NULL, '065', 'Dlhové cenné papiere držané do splatnosti', '0', 'asset', TRUE),
  (NULL, '066', 'Pôžičky účtovnej jednotke v konsolidovanom celku', '0', 'asset', TRUE),
  (NULL, '067', 'Ostatné pôžičky', '0', 'asset', TRUE),
  (NULL, '07', 'Oprávky k dlhodobému nehmotnému majetku', '0', 'asset', TRUE),
  (NULL, '071', 'Oprávky k zriaďovacím nákladom', '0', 'asset', TRUE),
  (NULL, '073', 'Oprávky k softvéru', '0', 'asset', TRUE),
  (NULL, '074', 'Oprávky k oceniteľným právam', '0', 'asset', TRUE),
  (NULL, '075', 'Oprávky ku goodwillu', '0', 'asset', TRUE),
  (NULL, '079', 'Oprávky k ostatnému DNM', '0', 'asset', TRUE),
  (NULL, '08', 'Oprávky k dlhodobému hmotnému majetku', '0', 'asset', TRUE),
  (NULL, '081', 'Oprávky k stavbám', '0', 'asset', TRUE),
  (NULL, '082', 'Oprávky k samostatným hnuteľným veciam', '0', 'asset', TRUE),
  (NULL, '083', 'Oprávky k dopravným prostriedkom', '0', 'asset', TRUE),
  (NULL, '089', 'Oprávky k ostatnému DHM', '0', 'asset', TRUE),
  (NULL, '09', 'Opravné položky k dlhodobému majetku', '0', 'asset', TRUE)
ON CONFLICT DO NOTHING;

-- Class 1 — Zásoby (Inventories)
INSERT INTO chart_of_accounts (organization_id, account_number, account_name, account_class, account_type, is_system) VALUES
  (NULL, '11', 'Materiál', '1', 'asset', TRUE),
  (NULL, '111', 'Obstaranie materiálu', '1', 'asset', TRUE),
  (NULL, '112', 'Materiál na sklade', '1', 'asset', TRUE),
  (NULL, '119', 'Materiál na ceste', '1', 'asset', TRUE),
  (NULL, '12', 'Zásoby vlastnej výroby', '1', 'asset', TRUE),
  (NULL, '121', 'Nedokončená výroba', '1', 'asset', TRUE),
  (NULL, '122', 'Polotovary vlastnej výroby', '1', 'asset', TRUE),
  (NULL, '123', 'Výrobky', '1', 'asset', TRUE),
  (NULL, '124', 'Zvieratá', '1', 'asset', TRUE),
  (NULL, '13', 'Tovar', '1', 'asset', TRUE),
  (NULL, '131', 'Obstaranie tovaru', '1', 'asset', TRUE),
  (NULL, '132', 'Tovar na sklade a v predajniach', '1', 'asset', TRUE),
  (NULL, '139', 'Tovar na ceste', '1', 'asset', TRUE),
  (NULL, '19', 'Opravné položky k zásobám', '1', 'asset', TRUE)
ON CONFLICT DO NOTHING;

-- Class 2 — Finančné účty (Financial Accounts)
INSERT INTO chart_of_accounts (organization_id, account_number, account_name, account_class, account_type, is_system) VALUES
  (NULL, '21', 'Peniaze', '2', 'asset', TRUE),
  (NULL, '211', 'Pokladnica', '2', 'asset', TRUE),
  (NULL, '213', 'Ceniny', '2', 'asset', TRUE),
  (NULL, '22', 'Účty v bankách', '2', 'asset', TRUE),
  (NULL, '221', 'Bankové účty', '2', 'asset', TRUE),
  (NULL, '23', 'Bežné bankové úvery', '2', 'liability', TRUE),
  (NULL, '231', 'Krátkodobé bankové úvery', '2', 'liability', TRUE),
  (NULL, '232', 'Eskontné úvery', '2', 'liability', TRUE),
  (NULL, '24', 'Krátkodobý finančný majetok', '2', 'asset', TRUE),
  (NULL, '241', 'Majetkové cenné papiere', '2', 'asset', TRUE),
  (NULL, '25', 'Krátkodobý finančný majetok', '2', 'asset', TRUE),
  (NULL, '251', 'Majetkové cenné papiere na obchodovanie', '2', 'asset', TRUE),
  (NULL, '253', 'Dlhové cenné papiere na obchodovanie', '2', 'asset', TRUE),
  (NULL, '255', 'Vlastné dlhopisy', '2', 'asset', TRUE),
  (NULL, '256', 'Ostatné realizovateľné cenné papiere', '2', 'asset', TRUE),
  (NULL, '259', 'Obstaranie krátkodobého finančného majetku', '2', 'asset', TRUE),
  (NULL, '26', 'Prevody medzi finančnými účtami', '2', 'asset', TRUE),
  (NULL, '261', 'Peniaze na ceste', '2', 'asset', TRUE),
  (NULL, '29', 'Opravné položky ku krátkodobému finančnému majetku', '2', 'asset', TRUE)
ON CONFLICT DO NOTHING;

-- Class 3 — Zúčtovacie vzťahy (Receivables & Payables)
INSERT INTO chart_of_accounts (organization_id, account_number, account_name, account_class, account_type, is_system) VALUES
  (NULL, '31', 'Pohľadávky', '3', 'asset', TRUE),
  (NULL, '311', 'Odberatelia', '3', 'asset', TRUE),
  (NULL, '312', 'Zmenky na inkaso', '3', 'asset', TRUE),
  (NULL, '313', 'Pohľadávky za eskontované cenné papiere', '3', 'asset', TRUE),
  (NULL, '314', 'Poskytnuté preddavky', '3', 'asset', TRUE),
  (NULL, '315', 'Ostatné pohľadávky', '3', 'asset', TRUE),
  (NULL, '32', 'Záväzky', '3', 'liability', TRUE),
  (NULL, '321', 'Dodávatelia', '3', 'liability', TRUE),
  (NULL, '322', 'Zmenky na úhradu', '3', 'liability', TRUE),
  (NULL, '324', 'Prijaté preddavky', '3', 'liability', TRUE),
  (NULL, '325', 'Ostatné záväzky', '3', 'liability', TRUE),
  (NULL, '33', 'Zúčtovanie so zamestnancami a orgánmi', '3', 'liability', TRUE),
  (NULL, '331', 'Zamestnanci', '3', 'liability', TRUE),
  (NULL, '335', 'Pohľadávky voči zamestnancom', '3', 'asset', TRUE),
  (NULL, '336', 'Zúčtovanie s orgánmi sociálneho poistenia a zdravotného poistenia', '3', 'liability', TRUE),
  (NULL, '34', 'Zúčtovanie daní a dotácií', '3', 'liability', TRUE),
  (NULL, '341', 'Daň z príjmov', '3', 'liability', TRUE),
  (NULL, '342', 'Ostatné priame dane', '3', 'liability', TRUE),
  (NULL, '343', 'Daň z pridanej hodnoty', '3', 'liability', TRUE),
  (NULL, '345', 'Ostatné dane a poplatky', '3', 'liability', TRUE),
  (NULL, '346', 'Dotácie zo štátneho rozpočtu', '3', 'asset', TRUE),
  (NULL, '347', 'Ostatné dotácie', '3', 'asset', TRUE),
  (NULL, '35', 'Pohľadávky voči spoločníkom', '3', 'asset', TRUE),
  (NULL, '351', 'Pohľadávky voči prepojeným účtovným jednotkám', '3', 'asset', TRUE),
  (NULL, '36', 'Záväzky voči spoločníkom', '3', 'liability', TRUE),
  (NULL, '361', 'Záväzky voči prepojeným účtovným jednotkám', '3', 'liability', TRUE),
  (NULL, '37', 'Iné pohľadávky a záväzky', '3', 'asset', TRUE),
  (NULL, '371', 'Pohľadávky z predaja podniku', '3', 'asset', TRUE),
  (NULL, '372', 'Záväzky z kúpy podniku', '3', 'liability', TRUE),
  (NULL, '374', 'Pohľadávky z nájmu', '3', 'asset', TRUE),
  (NULL, '375', 'Pohľadávky z vydaných dlhopisov', '3', 'asset', TRUE),
  (NULL, '378', 'Iné pohľadávky', '3', 'asset', TRUE),
  (NULL, '379', 'Iné záväzky', '3', 'liability', TRUE),
  (NULL, '38', 'Časové rozlíšenie nákladov a výnosov', '3', 'asset', TRUE),
  (NULL, '381', 'Náklady budúcich období', '3', 'asset', TRUE),
  (NULL, '382', 'Komplexné náklady budúcich období', '3', 'asset', TRUE),
  (NULL, '383', 'Výdavky budúcich období', '3', 'liability', TRUE),
  (NULL, '384', 'Výnosy budúcich období', '3', 'liability', TRUE),
  (NULL, '385', 'Príjmy budúcich období', '3', 'asset', TRUE),
  (NULL, '39', 'Opravná položka k zúčtovacím vzťahom a vnútorné zúčtovanie', '3', 'asset', TRUE),
  (NULL, '391', 'Opravné položky k pohľadávkam', '3', 'asset', TRUE),
  (NULL, '395', 'Vnútorné zúčtovanie', '3', 'asset', TRUE)
ON CONFLICT DO NOTHING;

-- Class 4 — Imanie a fondy (Equity & Funds)
INSERT INTO chart_of_accounts (organization_id, account_number, account_name, account_class, account_type, is_system) VALUES
  (NULL, '41', 'Základné imanie a kapitálové fondy', '4', 'equity', TRUE),
  (NULL, '411', 'Základné imanie', '4', 'equity', TRUE),
  (NULL, '412', 'Emisné ážio', '4', 'equity', TRUE),
  (NULL, '413', 'Ostatné kapitálové fondy', '4', 'equity', TRUE),
  (NULL, '414', 'Oceňovacie rozdiely z precenenia majetku a záväzkov', '4', 'equity', TRUE),
  (NULL, '415', 'Oceňovacie rozdiely z kapitálových účastín', '4', 'equity', TRUE),
  (NULL, '416', 'Oceňovacie rozdiely z precenenia pri zlúčení, splynutí a rozdelení', '4', 'equity', TRUE),
  (NULL, '42', 'Fondy zo zisku a prevedené výsledky hospodárenia', '4', 'equity', TRUE),
  (NULL, '421', 'Zákonný rezervný fond', '4', 'equity', TRUE),
  (NULL, '422', 'Nedeliteľný fond', '4', 'equity', TRUE),
  (NULL, '423', 'Štatutárne fondy', '4', 'equity', TRUE),
  (NULL, '427', 'Ostatné fondy', '4', 'equity', TRUE),
  (NULL, '428', 'Nerozdelený zisk minulých rokov', '4', 'equity', TRUE),
  (NULL, '429', 'Neuhradená strata minulých rokov', '4', 'equity', TRUE),
  (NULL, '43', 'Výsledok hospodárenia', '4', 'equity', TRUE),
  (NULL, '431', 'Výsledok hospodárenia v schvaľovaní', '4', 'equity', TRUE),
  (NULL, '45', 'Rezervy', '4', 'liability', TRUE),
  (NULL, '451', 'Rezervy zákonné', '4', 'liability', TRUE),
  (NULL, '459', 'Ostatné rezervy', '4', 'liability', TRUE),
  (NULL, '46', 'Dlhodobé bankové úvery', '4', 'liability', TRUE),
  (NULL, '461', 'Bankové úvery', '4', 'liability', TRUE),
  (NULL, '47', 'Dlhodobé záväzky', '4', 'liability', TRUE),
  (NULL, '471', 'Dlhodobé záväzky voči prepojeným účtovným jednotkám', '4', 'liability', TRUE),
  (NULL, '472', 'Záväzky zo sociálneho fondu', '4', 'liability', TRUE),
  (NULL, '473', 'Vydané dlhopisy', '4', 'liability', TRUE),
  (NULL, '474', 'Záväzky z nájmu', '4', 'liability', TRUE),
  (NULL, '475', 'Dlhodobé prijaté preddavky', '4', 'liability', TRUE),
  (NULL, '478', 'Dlhodobé zmenky na úhradu', '4', 'liability', TRUE),
  (NULL, '479', 'Ostatné dlhodobé záväzky', '4', 'liability', TRUE),
  (NULL, '48', 'Odložený daňový záväzok a odložená daňová pohľadávka', '4', 'liability', TRUE),
  (NULL, '481', 'Odložený daňový záväzok a odložená daňová pohľadávka', '4', 'liability', TRUE),
  (NULL, '49', 'Účty individuálneho podnikateľa', '4', 'equity', TRUE),
  (NULL, '491', 'Účet individuálneho podnikateľa', '4', 'equity', TRUE)
ON CONFLICT DO NOTHING;

-- Class 5 — Náklady (Expenses)
INSERT INTO chart_of_accounts (organization_id, account_number, account_name, account_class, account_type, is_system) VALUES
  (NULL, '50', 'Spotrebované nákupy', '5', 'expense', TRUE),
  (NULL, '501', 'Spotreba materiálu', '5', 'expense', TRUE),
  (NULL, '502', 'Spotreba energie', '5', 'expense', TRUE),
  (NULL, '503', 'Spotreba ostatných neskladovateľných dodávok', '5', 'expense', TRUE),
  (NULL, '504', 'Predaný tovar', '5', 'expense', TRUE),
  (NULL, '51', 'Služby', '5', 'expense', TRUE),
  (NULL, '511', 'Opravy a udržiavanie', '5', 'expense', TRUE),
  (NULL, '512', 'Cestovné', '5', 'expense', TRUE),
  (NULL, '513', 'Náklady na reprezentáciu', '5', 'expense', TRUE),
  (NULL, '518', 'Ostatné služby', '5', 'expense', TRUE),
  (NULL, '52', 'Osobné náklady', '5', 'expense', TRUE),
  (NULL, '521', 'Mzdové náklady', '5', 'expense', TRUE),
  (NULL, '524', 'Zákonné sociálne poistenie', '5', 'expense', TRUE),
  (NULL, '525', 'Ostatné sociálne poistenie', '5', 'expense', TRUE),
  (NULL, '527', 'Zákonné sociálne náklady', '5', 'expense', TRUE),
  (NULL, '528', 'Ostatné sociálne náklady', '5', 'expense', TRUE),
  (NULL, '53', 'Dane a poplatky', '5', 'expense', TRUE),
  (NULL, '531', 'Daň z motorových vozidiel', '5', 'expense', TRUE),
  (NULL, '532', 'Daň z nehnuteľností', '5', 'expense', TRUE),
  (NULL, '538', 'Ostatné dane a poplatky', '5', 'expense', TRUE),
  (NULL, '54', 'Iné prevádzkové náklady', '5', 'expense', TRUE),
  (NULL, '541', 'Zostatková cena predaného DM a materiálu', '5', 'expense', TRUE),
  (NULL, '542', 'Predaný materiál', '5', 'expense', TRUE),
  (NULL, '543', 'Dary', '5', 'expense', TRUE),
  (NULL, '544', 'Zmluvné pokuty a penále', '5', 'expense', TRUE),
  (NULL, '545', 'Ostatné pokuty a penále', '5', 'expense', TRUE),
  (NULL, '546', 'Odpis pohľadávky', '5', 'expense', TRUE),
  (NULL, '547', 'Tvorba a zúčtovanie opravných položiek', '5', 'expense', TRUE),
  (NULL, '548', 'Ostatné náklady na hospodársku činnosť', '5', 'expense', TRUE),
  (NULL, '549', 'Manká a škody', '5', 'expense', TRUE),
  (NULL, '55', 'Odpisy a opravné položky k DM', '5', 'expense', TRUE),
  (NULL, '551', 'Odpisy dlhodobého nehmotného majetku a dlhodobého hmotného majetku', '5', 'expense', TRUE),
  (NULL, '557', 'Zúčtovanie oprávky k opravnej položke k nadobudnutému majetku', '5', 'expense', TRUE),
  (NULL, '56', 'Finančné náklady', '5', 'expense', TRUE),
  (NULL, '561', 'Predané cenné papiere a podiely', '5', 'expense', TRUE),
  (NULL, '562', 'Úroky', '5', 'expense', TRUE),
  (NULL, '563', 'Kurzové straty', '5', 'expense', TRUE),
  (NULL, '564', 'Náklady na precenenie cenných papierov', '5', 'expense', TRUE),
  (NULL, '568', 'Ostatné finančné náklady', '5', 'expense', TRUE),
  (NULL, '569', 'Manká a škody na finančnom majetku', '5', 'expense', TRUE),
  (NULL, '59', 'Dane z príjmov a prevodové účty', '5', 'expense', TRUE),
  (NULL, '591', 'Splatná daň z príjmov', '5', 'expense', TRUE),
  (NULL, '592', 'Odložená daň z príjmov', '5', 'expense', TRUE),
  (NULL, '595', 'Dodatočné odvody dane z príjmov', '5', 'expense', TRUE)
ON CONFLICT DO NOTHING;

-- Class 6 — Výnosy (Revenue)
INSERT INTO chart_of_accounts (organization_id, account_number, account_name, account_class, account_type, is_system) VALUES
  (NULL, '60', 'Tržby za vlastné výkony a tovar', '6', 'revenue', TRUE),
  (NULL, '601', 'Tržby za vlastné výrobky', '6', 'revenue', TRUE),
  (NULL, '602', 'Tržby z predaja služieb', '6', 'revenue', TRUE),
  (NULL, '604', 'Tržby za tovar', '6', 'revenue', TRUE),
  (NULL, '61', 'Zmeny stavu vnútroorganizačných zásob', '6', 'revenue', TRUE),
  (NULL, '611', 'Zmena stavu nedokončenej výroby', '6', 'revenue', TRUE),
  (NULL, '612', 'Zmena stavu polotovarov', '6', 'revenue', TRUE),
  (NULL, '613', 'Zmena stavu výrobkov', '6', 'revenue', TRUE),
  (NULL, '614', 'Zmena stavu zvierat', '6', 'revenue', TRUE),
  (NULL, '62', 'Aktivácia', '6', 'revenue', TRUE),
  (NULL, '621', 'Aktivácia materiálu a tovaru', '6', 'revenue', TRUE),
  (NULL, '622', 'Aktivácia vnútroorganizačných služieb', '6', 'revenue', TRUE),
  (NULL, '623', 'Aktivácia dlhodobého nehmotného majetku', '6', 'revenue', TRUE),
  (NULL, '624', 'Aktivácia dlhodobého hmotného majetku', '6', 'revenue', TRUE),
  (NULL, '64', 'Iné prevádzkové výnosy', '6', 'revenue', TRUE),
  (NULL, '641', 'Tržby z predaja dlhodobého nehmotného majetku a dlhodobého hmotného majetku', '6', 'revenue', TRUE),
  (NULL, '642', 'Tržby z predaja materiálu', '6', 'revenue', TRUE),
  (NULL, '644', 'Zmluvné pokuty a penále', '6', 'revenue', TRUE),
  (NULL, '645', 'Ostatné pokuty a penále', '6', 'revenue', TRUE),
  (NULL, '646', 'Výnosy z odpísaných pohľadávok', '6', 'revenue', TRUE),
  (NULL, '648', 'Ostatné výnosy z hospodárskej činnosti', '6', 'revenue', TRUE),
  (NULL, '66', 'Finančné výnosy', '6', 'revenue', TRUE),
  (NULL, '661', 'Tržby z predaja cenných papierov a podielov', '6', 'revenue', TRUE),
  (NULL, '662', 'Úroky', '6', 'revenue', TRUE),
  (NULL, '663', 'Kurzové zisky', '6', 'revenue', TRUE),
  (NULL, '664', 'Výnosy z precenenia cenných papierov', '6', 'revenue', TRUE),
  (NULL, '665', 'Výnosy z dlhodobého finančného majetku', '6', 'revenue', TRUE),
  (NULL, '668', 'Ostatné finančné výnosy', '6', 'revenue', TRUE)
ON CONFLICT DO NOTHING;
